### ISSUE TITLE
No Longer Working

### ISSUE THREAD

**Issue by JakeyPrime** [JBoye/HACKTANE#6]
After a long time of not touching it, it's suddenly stopped working. I checked the mod settings and it looks the exact same, as well as it's the correct settings. I've tried repairing to the Hue Bridge, but nothing is working, and it's stuck on "Loading..." when the game boots.

This was what made me play the game, and I would love to play with it again.

**Comment by Xasin** [comment]
This might be because of the recent switch to allow for Linux architectures.
Linux handles Arduino connections in a very different manner, and I know that, while using KTANE via Wine worked very well, using HACKTANE on Wine produced the same "stuck on loading" behaviour.

My best guess is that KTANE changed some internal handling of the environment it's run in (Windows vs. Linux), and that that messes with how HACKTANE configures itself during loading ...

**Comment by JakeyPrime** [comment]
I'm using it on Windows 10, through the steam workshop. Which worked completely before, but I assume an update to either the game, or the add-on, broke it.
